In [1]:
from google.colab import files
uploaded = files.upload()
import pandas as pd

df = pd.read_csv("Sales Dataset.csv")  # Make sure filename matches!
print(df.head())

Saving Sales Dataset.csv to Sales Dataset.csv
  Order ID  Amount  Profit  Quantity     Category      Sub-Category  \
0  B-26776    9726    1275         5  Electronics  Electronic Games
1  B-26776    9726    1275         5  Electronics  Electronic Games
2  B-26776    9726    1275         5  Electronics  Electronic Games
3  B-26776    4975    1330        14  Electronics          Printers
4  B-26776    4975    1330        14  Electronics          Printers

  PaymentMode  Order Date   CustomerName     State     City Year-Month
0         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
1         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12
2         UPI  2021-07-25   Robert Stone  New York  Buffalo    2021-07
3         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
4         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12

In [2]:


#Handling Missing Data
import pandas as pd
# Show first few rows
print("🔍 First 5 Rows:")
print(df.head())

#  Check for missing values in each column
print("\n🧪 Missing Data (Count per Column):")
print(df.isna().sum())

#  Show rows with any missing values
print("\n📌 Rows with Missing Values:")
print(df[df.isna().any(axis=1)])

# Percentage of missing values per column
print("\n📊 Percentage of Missing Data:")
print((df.isna().sum() / len(df)) * 100)

# Drop rows with missing data (optional)
df_dropped = df.dropna()
print(f"\n✅ Data after dropping missing rows: {df_dropped.shape}")

#  Fill missing values (example: fill NaNs with 0)
df_filled = df.fillna(0)
print("\n📌 Data after filling missing values with 0:")
print(df_filled.head())

#  Fill missing values with forward fill (ffill)
df_ffill = df.fillna(method='ffill')
print("\n➡️ Forward Fill:")
print(df_ffill.head())

#  Fill missing values with backward fill (bfill)
df_bfill = df.fillna(method='bfill')
print("\n⬅️ Backward Fill:")
print(df_bfill.head())

🔍 First 5 Rows:
  Order ID  Amount  Profit  Quantity     Category      Sub-Category  \
0  B-26776    9726    1275         5  Electronics  Electronic Games
1  B-26776    9726    1275         5  Electronics  Electronic Games
2  B-26776    9726    1275         5  Electronics  Electronic Games
3  B-26776    4975    1330        14  Electronics          Printers
4  B-26776    4975    1330        14  Electronics          Printers

  PaymentMode  Order Date   CustomerName     State     City Year-Month
0         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
1         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12
2         UPI  2021-07-25   Robert Stone  New York  Buffalo    2021-07
3         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
4         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12

🧪 Missing Data (Count per Column):
Order ID        0
Amount          0
Profit          0
Quantity        0
Category        0
Sub-Category    0
PaymentMode     0
Order Date      0
CustomerName    0
State           0
City            0
Year-Month      0
dtype: int64

📌 Rows with Missing Values:
Empty DataFrame
Columns: [Order ID, Amount, Profit, Quantity, Category, Sub-Category, PaymentMode, Order Date, CustomerName, State, City, Year-Month]
Index: []

📊 Percentage of Missing Data:
Order ID        0.0
Amount          0.0
Profit          0.0
Quantity        0.0
Category        0.0
Sub-Category    0.0
PaymentMode     0.0
Order Date      0.0
CustomerName    0.0
State           0.0
City            0.0
Year-Month      0.0
dtype: float64

✅ Data after dropping missing rows: (1194, 12)

📌 Data after filling missing values with 0:
  Order ID  Amount  Profit  Quantity     Category      Sub-Category  \
0  B-26776    9726    1275         5  Electronics  Electronic Games
1  B-26776    9726    1275         5  Electronics  Electronic Games
2  B-26776    9726    1275         5  Electronics  Electronic Games
3  B-26776    4975    1330        14  Electronics          Printers
4  B-26776    4975    1330        14  Electronics          Printers

  PaymentMode  Order Date   CustomerName     State     City Year-Month
0         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
1         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12
2         UPI  2021-07-25   Robert Stone  New York  Buffalo    2021-07
3         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
4         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12

➡️ Forward Fill:
  Order ID  Amount  Profit  Quantity     Category      Sub-Category  \
0  B-26776    9726    1275         5  Electronics  Electronic Games
1  B-26776    9726    1275         5  Electronics  Electronic Games
2  B-26776    9726    1275         5  Electronics  Electronic Games
3  B-26776    4975    1330        14  Electronics          Printers
4  B-26776    4975    1330        14  Electronics          Printers

  PaymentMode  Order Date   CustomerName     State     City Year-Month
0         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
1         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12
2         UPI  2021-07-25   Robert Stone  New York  Buffalo    2021-07
3         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
4         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12

⬅️ Backward Fill:
  Order ID  Amount  Profit  Quantity     Category      Sub-Category  \
0  B-26776    9726    1275         5  Electronics  Electronic Games
1  B-26776    9726    1275         5  Electronics  Electronic Games
2  B-26776    9726    1275         5  Electronics  Electronic Games
3  B-26776    4975    1330        14  Electronics          Printers
4  B-26776    4975    1330        14  Electronics          Printers

  PaymentMode  Order Date   CustomerName     State     City Year-Month
0         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
1         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12
2         UPI  2021-07-25   Robert Stone  New York  Buffalo    2021-07
3         UPI  2023-06-27  David Padilla   Florida    Miami    2023-06
4         UPI  2024-12-27  Connor Morgan  Illinois  Chicago    2024-12

<ipython-input-2-e89396e4a5ca>:29: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_ffill = df.fillna(method='ffill')
<ipython-input-2-e89396e4a5ca>:34: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_bfill = df.fillna(method='bfill')

In [3]:
#Filtering Out Missing Data
import pandas as pd
import numpy as np

# Series example
series_data = pd.Series([1, np.nan, 3.5, np.nan, 7])

# Drop missing values using dropna
clean_series = series_data.dropna()

# Same result using boolean indexing with notna
clean_series_alt = series_data[series_data.notna()]

print("Original Series:\n", series_data)
print("\nCleaned Series using dropna:\n", clean_series)
print("\nCleaned Series using notna:\n", clean_series_alt)

# DataFrame example
df = pd.DataFrame([
    [1.0, 6.5, 3.0],
    [1.0, np.nan, np.nan],
    [np.nan, np.nan, np.nan],
    [np.nan, 6.5, 3.0]
])

# Drop rows with any NaNs
dropped_any_na = df.dropna()

# Drop rows where all values are NaN
dropped_all_na = df.dropna(how='all')

# Add a column with all NaNs
df[3] = np.nan

# Drop columns where all values are NaN
dropped_columns_all_na = df.dropna(axis='columns', how='all')

# Keep rows with at least 2 non-NaN values using thresh
df2 = pd.DataFrame(np.random.randn(7, 3))
df2.iloc[:4, 1] = np.nan
df2.iloc[:2, 2] = np.nan
dropped_thresh = df2.dropna(thresh=2)

# Display results
print("\nOriginal DataFrame:\n", df)
print("\nDropped rows with any NaNs:\n", dropped_any_na)
print("\nDropped rows with all NaNs:\n", dropped_all_na)
print("\nDropped columns with all NaNs:\n", dropped_columns_all_na)
print("\nDataFrame with thresh=2:\n", dropped_thresh)

Original Series:
 0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

Cleaned Series using dropna:
 0    1.0
2    3.5
4    7.0
dtype: float64

Cleaned Series using notna:
 0    1.0
2    3.5
4    7.0
dtype: float64

Original DataFrame:
      0    1    2   3
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

Dropped rows with any NaNs:
      0    1    2
0  1.0  6.5  3.0

Dropped rows with all NaNs:
      0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

Dropped columns with all NaNs:
      0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

DataFrame with thresh=2:
           0         1         2
2 -0.626259       NaN  0.704960
3 -0.542976       NaN -0.615918
4  1.603599 -0.606925 -1.494410
5  0.431897 -1.785862 -0.928021
6 -0.217297 -1.135677 -0.387568

In [4]:
#Filling In Missing Data
import pandas as pd
import numpy as np

# Sample DataFrame with missing values
df = pd.DataFrame({
    0: [0.1, -0.2, 0.3, np.nan, 0.5, np.nan],
    1: [np.nan, 0.6, np.nan, np.nan, 0.9, -1.1],
    2: [1.2, np.nan, 0.8, -0.3, np.nan, np.nan]
})

print("Original DataFrame:\n", df)

# Fill missing values with a constant
filled_constant = df.fillna(0)
print("\nFilled with constant 0:\n", filled_constant)

# Fill missing values with different values per column
filled_dict = df.fillna({1: 0.5, 2: 0})
print("\nFilled with column-specific values:\n", filled_dict)

# Forward fill method
filled_ffill = df.fillna(method="ffill")
print("\nForward fill:\n", filled_ffill)

# Forward fill with a limit
filled_ffill_limit = df.fillna(method="ffill", limit=1)
print("\nForward fill with limit=1:\n", filled_ffill_limit)

# Fill with column mean (example using a Series)
s = pd.Series([1., np.nan, 3.5, np.nan, 7])
filled_mean = s.fillna(s.mean())
print("\nSeries filled with mean:\n", filled_mean)

Original DataFrame:
      0    1    2
0  0.1  NaN  1.2
1 -0.2  0.6  NaN
2  0.3  NaN  0.8
3  NaN  NaN -0.3
4  0.5  0.9  NaN
5  NaN -1.1  NaN

Filled with constant 0:
      0    1    2
0  0.1  0.0  1.2
1 -0.2  0.6  0.0
2  0.3  0.0  0.8
3  0.0  0.0 -0.3
4  0.5  0.9  0.0
5  0.0 -1.1  0.0

Filled with column-specific values:
      0    1    2
0  0.1  0.5  1.2
1 -0.2  0.6  0.0
2  0.3  0.5  0.8
3  NaN  0.5 -0.3
4  0.5  0.9  0.0
5  NaN -1.1  0.0

Forward fill:
      0    1    2
0  0.1  NaN  1.2
1 -0.2  0.6  1.2
2  0.3  0.6  0.8
3  0.3  0.6 -0.3
4  0.5  0.9 -0.3
5  0.5 -1.1 -0.3

Forward fill with limit=1:
      0    1    2
0  0.1  NaN  1.2
1 -0.2  0.6  1.2
2  0.3  0.6  0.8
3  0.3  NaN -0.3
4  0.5  0.9 -0.3
5  0.5 -1.1  NaN

Series filled with mean:
 0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

<ipython-input-4-546ca708a952>:23: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  filled_ffill = df.fillna(method="ffill")
<ipython-input-4-546ca708a952>:27: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  filled_ffill_limit = df.fillna(method="ffill", limit=1)

In [5]:
#Data Transformation
import pandas as pd

# Sample sales dataset
data = pd.DataFrame({
    "product": ["laptop", "tablet", "phone", "laptop", "tablet", "phone", "headphones"],
    "sales": [1000, 500, 750, 1000, 500, 750, 300],
    "region": ["North", "East", "South", "North", "East", "South", "West"]
})

# Display the original data
print("Original Data:")
print(data)

# Detect duplicates
duplicates = data.duplicated()
print("\nDuplicated Rows:")
print(duplicates)

# Drop duplicates
cleaned_data = data.drop_duplicates()
print("\nData After Removing Duplicates:")
print(cleaned_data)

Original Data:
      product  sales region
0      laptop   1000  North
1      tablet    500   East
2       phone    750  South
3      laptop   1000  North
4      tablet    500   East
5       phone    750  South
6  headphones    300   West

Duplicated Rows:
0    False
1    False
2    False
3     True
4     True
5     True
6    False
dtype: bool

Data After Removing Duplicates:
      product  sales region
0      laptop   1000  North
1      tablet    500   East
2       phone    750  South
6  headphones    300   West

In [6]:
#Replacing Values
#Renaming Axis Indexes
import pandas as pd
import numpy as np

# Sample sales dataset
data = pd.DataFrame({
    "product": ["laptop", "tablet", "phone", "laptop", "tablet", "phone", "headphones"],
    "sales": [1000, 500, -999, 1000, -999, 750, 300],
    "region": ["North", "East", "South", "North", "East", "South", "West"]
})

# Display the original data
print("Original Data:")
print(data)

# 1. Replacing -999 with NaN in the 'sales' column
data["sales"] = data["sales"].replace(-999, np.nan)

# Replace NaN values in 'sales' column with the mean of 'sales'
mean_sales = data["sales"].mean()
data["sales"].fillna(mean_sales, inplace=True)

# Display the data after replacing values
print("\nData After Replacing -999 with NaN and filling NaN with mean sales value:")
print(data)

# 2. Renaming the columns and index (row labels)
data.rename(index={"North": "NORTH_REGION", "East": "EAST_REGION", "South": "SOUTH_REGION", "West": "WEST_REGION"},
            columns={"product": "product_name", "sales": "sales_amount", "region": "sales_region"}, inplace=True)

# Display the data after renaming axis indexes
print("\nData After Renaming Index and Columns:")
print(data)

# 3. Function to categorize sales
def categorize_sales(row):
    if row['sales_amount'] > 800:
        return "High Sales"
    elif 500 <= row['sales_amount'] <= 800:
        return "Medium Sales"
    else:
        return "Low Sales"

# Apply the function to categorize sales based on the sales_amount
data["sales_category"] = data.apply(categorize_sales, axis=1)

# Display the final transformed data
print("\nData After Categorizing Sales:")
print(data)

Original Data:
      product  sales region
0      laptop   1000  North
1      tablet    500   East
2       phone   -999  South
3      laptop   1000  North
4      tablet   -999   East
5       phone    750  South
6  headphones    300   West

Data After Replacing -999 with NaN and filling NaN with mean sales value:
      product   sales region
0      laptop  1000.0  North
1      tablet   500.0   East
2       phone   710.0  South
3      laptop  1000.0  North
4      tablet   710.0   East
5       phone   750.0  South
6  headphones   300.0   West

Data After Renaming Index and Columns:
  product_name  sales_amount sales_region
0       laptop        1000.0        North
1       tablet         500.0         East
2        phone         710.0        South
3       laptop        1000.0        North
4       tablet         710.0         East
5        phone         750.0        South
6   headphones         300.0         West

Data After Categorizing Sales:
  product_name  sales_amount sales_region sales_category
0       laptop        1000.0        North     High Sales
1       tablet         500.0         East   Medium Sales
2        phone         710.0        South   Medium Sales
3       laptop        1000.0        North     High Sales
4       tablet         710.0         East   Medium Sales
5        phone         750.0        South   Medium Sales
6   headphones         300.0         West      Low Sales

<ipython-input-6-540a5055586c>:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["sales"].fillna(mean_sales, inplace=True)

In [7]:
# Binning and Discretization:
import pandas as pd
import numpy as np

# Sample sales dataset
sales = [1000, 500, 999, 1200, 800, 750, 300, 1200, 1500, 2000, 1000, 900]
sales_df = pd.DataFrame(sales, columns=["sales"])

# Define bins for sales: you can change the ranges to suit your data
bins = [0, 500, 1000, 1500, 2500]
bin_labels = ["Low", "Medium", "High", "Very High"]

# Use pd.cut to categorize the sales into bins
sales_categories = pd.cut(sales_df["sales"], bins=bins, labels=bin_labels, right=False)

# Add the new category column to the DataFrame
sales_df["sales_category"] = sales_categories

print("Sales Dataset with Categories:")
print(sales_df)

Sales Dataset with Categories:
    sales sales_category
0    1000           High
1     500         Medium
2     999         Medium
3    1200           High
4     800         Medium
5     750         Medium
6     300            Low
7    1200           High
8    1500      Very High
9    2000      Very High
10   1000           High
11    900         Medium

In [8]:
#Permutation and Random Sampling and computing indicators and variables
import numpy as np

# Example sales dataset
data = {
    'Product': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Sales': [120, 250, 300, 400, 150, 220],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South']
}

df = pd.DataFrame(data)

# 1. Random Sampling without replacement (3 samples)
sampled_data = df.sample(n=3)
print("Random Sampled Data:")
print(sampled_data)
print("\n")

# 2. Creating Dummy Variables for the 'Region' column
dummies = pd.get_dummies(df['Region'], prefix='Region')
df_with_dummies = df.join(dummies)
print("Data with Dummy Variables:")
print(df_with_dummies)
print("\n")

# 3. Permuting Rows
row_sampler = np.random.permutation(df.shape[0])  # Number of rows
permuted_rows = df.take(row_sampler)
print("Permuted Rows:")
print(permuted_rows)
print("\n")

# 4. Permuting Columns
column_sampler = np.random.permutation(df.shape[1])  # Number of columns
permuted_columns = df.take(column_sampler, axis='columns')
print("Permuted Columns:")
print(permuted_columns)

import numpy as np

# Example sales dataset
data = {
    'Product': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Sales': [120, 250, 300, 400, 150, 220],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South']
}

df = pd.DataFrame(data)

# 1. Random Sampling without replacement (3 samples)
sampled_data = df.sample(n=3)
print("Random Sampled Data:")
print(sampled_data)
print("\n")

# 2. Creating Dummy Variables for the 'Region' column
dummies = pd.get_dummies(df['Region'], prefix='Region')
df_with_dummies = df.join(dummies)
print("Data with Dummy Variables:")
print(df_with_dummies)
print("\n")

# 3. Permuting Rows
row_sampler = np.random.permutation(df.shape[0])  # Number of rows
permuted_rows = df.take(row_sampler)
print("Permuted Rows:")
print(permuted_rows)
print("\n")

# 4. Permuting Columns
column_sampler = np.random.permutation(df.shape[1])  # Number of columns
permuted_columns = df.take(column_sampler, axis='columns')
print("Permuted Columns:")
print(permuted_columns)

import pandas as pd
import numpy as np

# Example sales dataset
data = {
    'Product': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Sales': [120, 250, 300, 400, 150, 220],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South']
}

df = pd.DataFrame(data)

# 1. Random Sampling without replacement (3 samples)
sampled_data = df.sample(n=3)
print("Random Sampled Data:")
print(sampled_data)
print("\n")

# 2. Creating Dummy Variables for the 'Region' column
dummies = pd.get_dummies(df['Region'], prefix='Region')
df_with_dummies = df.join(dummies)
print("Data with Dummy Variables:")
print(df_with_dummies)
print("\n")

# 3. Permuting Rows
row_sampler = np.random.permutation(df.shape[0])  # Number of rows
permuted_rows = df.take(row_sampler)
print("Permuted Rows:")
print(permuted_rows)
print("\n")

# 4. Permuting Columns
column_sampler = np.random.permutation(df.shape[1])  # Number of columns
permuted_columns = df.take(column_sampler, axis='columns')
print("Permuted Columns:")
print(permuted_columns)

Random Sampled Data:
  Product  Sales Region
5       F    220  South
2       C    300   East
4       E    150  North


Data with Dummy Variables:
  Product  Sales Region  Region_East  Region_North  Region_South  Region_West
0       A    120  North        False          True         False        False
1       B    250  South        False         False          True        False
2       C    300   East         True         False         False        False
3       D    400   West        False         False         False         True
4       E    150  North        False          True         False        False
5       F    220  South        False         False          True        False


Permuted Rows:
  Product  Sales Region
2       C    300   East
3       D    400   West
0       A    120  North
5       F    220  South
4       E    150  North
1       B    250  South


Permuted Columns:
   Sales Region Product
0    120  North       A
1    250  South       B
2    300   East       C
3    400   West       D
4    150  North       E
5    220  South       F

In [9]:
import pandas as pd
import re

# Sample Sales Data
data = {
    'Product': ['Apple', 'Banana', 'Orange', 'Grapes'],
    'Description': ['Fresh and juicy apple', 'Sweet yellow banana', 'Tasty and fresh orange', 'Green and sweet grapes'],
    'Price': ['10.99', '5.50', '8.75', '12.00']
}

# Create DataFrame
df = pd.DataFrame(data)

# 1. String Manipulation: Convert 'Price' column to float
df['Price'] = df['Price'].astype(float)

# 2. String Manipulation: Replace words in 'Description' column
df['Description'] = df['Description'].str.replace('fresh', 'delicious')

# 3. Regex: Extract product names that contain the letter 'e' from 'Description'
regex_pattern = r"\b\w*e\w*\b"  # Matches words containing the letter 'e'
df['Words_with_e'] = df['Description'].apply(lambda x: re.findall(regex_pattern, x))

# 4. Regex: Find prices greater than 8 and mark them as 'High' or 'Low'
df['Price_Category'] = df['Price'].apply(lambda x: 'High' if x > 8 else 'Low')

# 5. String Manipulation: Concatenate 'Product' and 'Price' into a new column
df['Product_Info'] = df['Product'] + " - " + df['Price'].astype(str)

# Display the DataFrame
print(df)

  Product                 Description  Price            Words_with_e  \
0   Apple       Fresh and juicy apple  10.99          [Fresh, apple]
1  Banana         Sweet yellow banana   5.50         [Sweet, yellow]
2  Orange  Tasty and delicious orange   8.75     [delicious, orange]
3  Grapes      Green and sweet grapes  12.00  [Green, sweet, grapes]

  Price_Category   Product_Info
0           High  Apple - 10.99
1            Low   Banana - 5.5
2           High  Orange - 8.75
3           High  Grapes - 12.0

In [11]:
import pandas as pd
import re




# 1. String Manipulation: Convert 'Price' column to float (adjust column name if needed)
df['Price'] = df['Price'].astype(float)

# 2. String Manipulation: Replace words in 'Description' column (adjust column name if needed)
df['Description'] = df['Description'].str.replace('fresh', 'delicious')

# 3. Regex: Extract product names that contain the letter 'e' from 'Description'
regex_pattern = r"\b\w*e\w*\b"  # Matches words containing the letter 'e'
df['Words_with_e'] = df['Description'].apply(lambda x: re.findall(regex_pattern, x))

# 4. Regex: Find prices greater than 8 and mark them as 'High' or 'Low'
df['Price_Category'] = df['Price'].apply(lambda x: 'High' if x > 8 else 'Low')

# 5. String Manipulation: Concatenate 'Product' and 'Price' into a new column
df['Product_Info'] = df['Product'] + " - " + df['Price'].astype(str)

# Display the updated DataFrame
print(df)

  Product                 Description  Price            Words_with_e  \
0   Apple       Fresh and juicy apple  10.99          [Fresh, apple]
1  Banana         Sweet yellow banana   5.50         [Sweet, yellow]
2  Orange  Tasty and delicious orange   8.75     [delicious, orange]
3  Grapes      Green and sweet grapes  12.00  [Green, sweet, grapes]

  Price_Category   Product_Info
0           High  Apple - 10.99
1            Low   Banana - 5.5
2           High  Orange - 8.75
3           High  Grapes - 12.0

In [13]:
import pandas as pd
import re



# 1. String Manipulation: Convert 'Price' column to float (adjust column name if needed)
df['Price'] = df['Price'].astype(float)

# 2. String Manipulation: Replace words in 'Description' column (adjust column name if needed)
df['Description'] = df['Description'].str.replace('fresh', 'delicious')

# 3. Regex: Extract product names that contain the letter 'e' from 'Description'
regex_pattern = r"\b\w*e\w*\b"  # Matches words containing the letter 'e'
df['Words_with_e'] = df['Description'].apply(lambda x: re.findall(regex_pattern, x))

# 4. Regex: Find prices greater than 8 and mark them as 'High' or 'Low'
df['Price_Category'] = df['Price'].apply(lambda x: 'High' if x > 8 else 'Low')

# 5. String Manipulation: Concatenate 'Product' and 'Price' into a new column
df['Product_Info'] = df['Product'] + " - " + df['Price'].astype(str)

# Display the updated DataFrame
print(df)

  Product                 Description  Price            Words_with_e  \
0   Apple       Fresh and juicy apple  10.99          [Fresh, apple]
1  Banana         Sweet yellow banana   5.50         [Sweet, yellow]
2  Orange  Tasty and delicious orange   8.75     [delicious, orange]
3  Grapes      Green and sweet grapes  12.00  [Green, sweet, grapes]

  Price_Category   Product_Info
0           High  Apple - 10.99
1            Low   Banana - 5.5
2           High  Orange - 8.75
3           High  Grapes - 12.0